import { useRef, useState, type PointerEvent } from 'react'
import entryDesktop from './assets/room/studio-desktop-v2.webp'
import entryMobile from './assets/room/studio-mobile-v2.webp'
import automationDesktop from './assets/cinematic/automation-desk-desktop-v2.webp'
import automationMobile from './assets/cinematic/automation-desk-mobile-v2.webp'
import aboutDesktop from './assets/cinematic/about-window-desktop-v2.webp'
import aboutMobile from './assets/cinematic/about-chair-mobile-v2.webp'

type View = 'home' | 'projects' | 'about'
type Project = { id: string; number: string; title: string; eyebrow: string; description: string; challenge: string; outcome: string; proof: string; status: string; repository: string; stack: string[]; tone: 'amber' | 'blue' | 'green'; flow: string[]; impact?: { title: string; detail: string }[] }

const projects: Project[] = [
  { id: 'legal-docs', number: '01', eyebrow: 'AUTOMATIZACIÓN JURÍDICA · IMPACTO REAL', title: 'Solicitudes legales', description: 'Devuelve horas de trabajo cada semana a una oficina de abogados al eliminar gran parte de la preparación manual de solicitudes y documentos.', challenge: 'El equipo legal invertía tiempo profesional en redactar documentos repetitivos, completar campos variables y comprobar una y otra vez el formato institucional.', outcome: 'Los abogados preparan solicitudes con mayor rapidez y consistencia, reducen trabajo administrativo y pueden dedicar más tiempo al análisis jurídico y a sus clientes.', proof: 'Automatización actualmente en funcionamiento dentro de una oficina de abogados. Estandariza cinco tipos de solicitudes y entrega documentos listos para revisión profesional.', status: 'Sistema en funcionamiento', repository: 'https://github.com/yeisondev001/sistema-de-solicitudes-legales', stack: ['Python', 'Flet', 'python-docx'], tone: 'amber', flow: ['Datos del caso', 'Validación automática', 'Documento preparado', 'Revisión profesional'], impact: [{ title: 'Horas recuperadas', detail: 'cada semana para el equipo legal' }, { title: 'Menos trabajo manual', detail: 'en redacción y digitación repetitiva' }, { title: 'Mayor consistencia', detail: 'en formatos y solicitudes' }, { title: 'Más enfoque jurídico', detail: 'en casos, estrategia y clientes' }] },
  { id: 'inventory', number: '02', eyebrow: 'OPERACIONES SAAS', title: 'Inventario multi-tienda', description: 'Centraliza productos, almacenes y movimientos para varias tiendas sin mezclar sus datos.', challenge: 'Operar múltiples clientes desde una sola plataforma manteniendo seguridad, roles y aislamiento por tienda.', outcome: 'Una API multi-tenant con autenticación JWT, permisos por rol y trazabilidad de movimientos de inventario.', proof: 'Incluye API documentada, pruebas, migraciones, despliegue con Docker y paneles separados para cada rol.', status: 'Repositorio disponible', repository: 'https://github.com/yeisondev001/Inventario', stack: ['.NET 8', 'SQL Server', 'JWT'], tone: 'blue', flow: ['Usuario se autentica', 'Tenant se identifica', 'Movimiento se registra', 'Stock se actualiza'] },
  { id: 'appointments', number: '03', eyebrow: 'RESERVAS Y API', title: 'Gestión de citas', description: 'Organiza disponibilidad, usuarios y reservas mediante una arquitectura preparada para crecer.', challenge: 'Evitar reservas duplicadas y sustituir la gestión manual por un proceso centralizado y seguro.', outcome: 'Una solución por capas con autenticación, persistencia en SQL Server y una API REST para integraciones.', proof: 'Proyecto desarrollado con arquitectura Onion y separación entre dominio, aplicación, infraestructura y presentación.', status: 'Repositorio disponible', repository: 'https://github.com/yeisondev001/Appointment-Booking', stack: ['C#', 'ASP.NET', 'SQL Server'], tone: 'green', flow: ['Usuario accede', 'Horario se valida', 'Cita se reserva', 'Agenda se actualiza'] },
]
const stack = ['n8n', 'Make', 'OpenAI', 'Python', 'APIs', 'PostgreSQL']

function Icon({ name }: { name: 'home' | 'folder' | 'user' | 'arrow' | 'mail' | 'close' | 'github' | 'link' | 'spark' | 'download' }) {
  const props = { viewBox: '0 0 24 24', 'aria-hidden': true }
  if (name === 'home') return <svg {...props}><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z" /></svg>
  if (name === 'folder') return <svg {...props}><path d="M3.5 6.5h6l1.8 2H20a1.5 1.5 0 0 1 1.5 1.5v8A1.5 1.5 0 0 1 20 19.5H4A1.5 1.5 0 0 1 2.5 18V8a1.5 1.5 0 0 1 1-1.5Z" /></svg>
  if (name === 'user') return <svg {...props}><circle cx="12" cy="8" r="3.5" /><path d="M4.5 21c.8-4 3.3-6 7.5-6s6.7 2 7.5 6" /></svg>
  if (name === 'mail') return <svg {...props}><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m4 7 8 6 8-6" /></svg>
  if (name === 'close') return <svg {...props}><path d="m6 6 12 12M18 6 6 18" /></svg>
  if (name === 'github') return <svg {...props}><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.9c0-1.1.1-1.6-.5-2.2 2.1-.2 4.4-1 4.4-5a3.9 3.9 0 0 0-1.1-2.7 3.6 3.6 0 0 0-.1-2.7s-.8-.3-2.8 1.1a9.7 9.7 0 0 0-5 0C8.9 5.2 8.1 5.5 8.1 5.5A3.6 3.6 0 0 0 8 8.2a3.9 3.9 0 0 0-1.1 2.7c0 4 2.3 4.8 4.4 5-.6.6-.6 1.3-.6 2.2V22" /></svg>
  if (name === 'link') return <svg {...props}><path d="M10 14a4.5 4.5 0 0 0 6.4.1l2.1-2.1a4.5 4.5 0 0 0-6.4-6.4L11 6.7" /><path d="M14 10a4.5 4.5 0 0 0-6.4-.1l-2.1 2.1a4.5 4.5 0 0 0 6.4 6.4l1.1-1.1" /></svg>
  if (name === 'spark') return <svg {...props}><path d="m12 2 1.8 6.2L20 10l-6.2 1.8L12 18l-1.8-6.2L4 10l6.2-1.8L12 2Z" /></svg>
  if (name === 'download') return <svg {...props}><path d="M12 3v12" /><path d="m7 10 5 5 5-5" /><path d="M4 20h16" /></svg>
  return <span aria-hidden="true">→</span>
}

function ScenePhoto({ desktop, mobile, active, name }: { desktop: string; mobile: string; active: boolean; name: string }) {
  return <picture className={`scene-photo scene-photo-${name} ${active ? 'is-active' : ''}`} style={{ '--scene-backdrop': `url(${desktop})` } as React.CSSProperties} aria-hidden={!active}><source media="(max-width: 700px)" srcSet={mobile} /><img src={desktop} alt="" /><span className={`scene-vignette vignette-${name}`} /></picture>
}

function App() {
  const [view, setView] = useState<View>('home')
  const [selected, setSelected] = useState<Project | null>(null)
  const surface = useRef<HTMLElement>(null)
  const go = (next: View) => { setSelected(null); setView(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const moveCamera = (event: PointerEvent<HTMLElement>) => { if (event.pointerType === 'touch') return; const rect = event.currentTarget.getBoundingClientRect(); surface.current?.style.setProperty('--scene-x', `${((event.clientX - rect.left) / rect.width - .5) * -14}px`); surface.current?.style.setProperty('--scene-y', `${((event.clientY - rect.top) / rect.height - .5) * -10}px`) }
  const resetCamera = () => { surface.current?.style.setProperty('--scene-x', '0px'); surface.current?.style.setProperty('--scene-y', '0px') }
  return <main ref={surface} onPointerMove={moveCamera} onPointerLeave={resetCamera} className={`portfolio scene-${view}`}>
    <div className="scene-stage"><ScenePhoto name="entry" desktop={entryDesktop} mobile={entryMobile} active={view === 'home'} /><ScenePhoto name="projects" desktop={automationDesktop} mobile={automationMobile} active={view === 'projects'} /><ScenePhoto name="about" desktop={aboutDesktop} mobile={aboutMobile} active={view === 'about'} /><div className="ambient-light amber-light" /><div className="ambient-light blue-light" /><div className="film-grain" /></div>
    <header className="site-header"><button className="identity" onClick={() => go('home')} aria-label="Volver a la entrada"><span className="identity-mark" /><b>YEISON ROJAS</b><small>AUTOMATION SYSTEMS</small></button><nav className="header-actions" aria-label="Enlaces profesionales"><a href="https://github.com/yeisondev001" target="_blank" rel="noreferrer"><Icon name="github" /><span>GitHub</span></a><a href="mailto:yeisonrojas03@gmail.com"><Icon name="mail" /><span>Gmail</span></a><a className="cv-download" href="/cv/yeison-rojas-cv.pdf" download><Icon name="download" /><span>CV</span></a></nav></header>
    {view === 'home' && <Home go={go} />}{view === 'projects' && <Projects go={go} openProject={setSelected} />}{view === 'about' && <About go={go} />}
    <nav className="dock" aria-label="Navegación del portafolio"><button className={view === 'projects' ? 'active' : ''} onClick={() => go('projects')}><Icon name="folder" /><span>Portafolio</span></button><button className={view === 'home' ? 'active' : ''} onClick={() => go('home')}><Icon name="home" /><span>Entrada</span></button><button className={view === 'about' ? 'active' : ''} onClick={() => go('about')}><Icon name="user" /><span>Sobre mí</span></button></nav>
    {selected && <ProjectDialog project={selected} close={() => setSelected(null)} />}
  </main>
}

function Home({ go }: { go: (view: View) => void }) { return <section className="home-view" aria-label="Entrada del portafolio"><div className="intro-card"><p className="kicker">SISTEMAS + AUTOMATIZACIÓN</p><h1>Sistemas que<br /><em>trabajan contigo.</em></h1><p>Construyo soluciones que conectan procesos, datos y software, preparadas para incorporar inteligencia artificial donde aporta valor real.</p><button className="text-action" onClick={() => go('projects')}>Entrar al portafolio <Icon name="arrow" /></button></div><button className="scene-hotspot home-project-link" onClick={() => go('projects')}><span><Icon name="spark" /></span><b>Estación de trabajo</b><small>Ver proyectos reales</small></button><p className="scene-hint">Mueve el cursor para explorar el estudio <span>•</span> cada estación cuenta una parte de la historia</p></section> }
function Back({ go }: { go: (view: View) => void }) { return <button className="back" onClick={() => go('home')}>← <span>Volver al estudio</span></button> }
function SceneMoment({ desktop, mobile, caption }: { desktop: string; mobile: string; caption: string }) { return <figure className="scene-moment"><picture><source media="(max-width: 700px)" srcSet={mobile} /><img src={desktop} alt="" /></picture><figcaption>{caption}</figcaption></figure> }
function Projects({ go, openProject }: { go: (view: View) => void; openProject: (project: Project) => void }) { return <section className="content-view projects-view"><Back go={go} /><SceneMoment desktop={automationDesktop} mobile={automationMobile} caption="01 — ESTACIÓN DE AUTOMATIZACIÓN" /><div className="content-heading"><p className="kicker">ESTACIÓN 01 · ESCRITORIO</p><h1>Sistemas reales<br /><em>que escalan.</em></h1><p>Proyectos construidos para automatizar documentos, organizar operaciones y conectar servicios mediante APIs.</p></div><div className="project-list">{projects.map((project, index) => <ProjectCard project={project} key={project.id} index={index} open={() => openProject(project)} />)}</div></section> }
function ProjectCard({ project, index, open }: { project: Project; index: number; open: () => void }) { return <article className={`project-card ${project.tone}`} style={{ '--delay': `${index * 90}ms` } as React.CSSProperties}><button className="project-click-target" onClick={open} aria-label={`Abrir ${project.title}`} /><div className="project-art"><span>{project.number}</span><i /><i /><i /></div><div className="card-copy"><p className="card-eyebrow">{project.eyebrow}</p><h2>{project.title}</h2><p>{project.description}</p><div>{project.stack.map(item => <span className="tag" key={item}>{item}</span>)}</div></div><span className="card-arrow"><Icon name="arrow" /></span></article> }
function About({ go }: { go: (view: View) => void }) {
  return <section className="content-view about-view"><Back go={go} /><SceneMoment desktop={aboutDesktop} mobile={aboutMobile} caption="02 — PERFIL / NOCHE EN EL ESTUDIO" /><div className="content-heading"><p className="kicker">ESTACIÓN 02 · PERFIL</p><h1>Construyo<br /><em>con intención.</em></h1><p>Combino automatización, desarrollo e IA para convertir operaciones complejas en sistemas simples, visibles y medibles.</p></div><div className="profile-note"><div><span>01</span><p>Entender el proceso real antes de conectar herramientas.</p></div><div><span>02</span><p>Diseñar flujos claros que el equipo pueda mantener.</p></div><div><span>03</span><p>Medir, aprender y mejorar con datos.</p></div></div><section className="stack-block"><p className="detail-label">STACK DE TRABAJO</p><div>{stack.map(item => <span key={item}>{item}</span>)}</div></section><section className="timeline"><p className="detail-label">TRAYECTORIA</p><article><small>2026 — HOY</small><h2>Automatización con IA</h2><p>Flujos, asistentes y sistemas conectados que resuelven trabajo real.</p></article><article><small>2025 — 2026</small><h2>Datos & desarrollo</h2><p>Fundamentos técnicos para integrar APIs, bases de datos y experiencias web.</p></article></section><div className="contact-card" id="contacto"><div><p className="kicker">¿HABLAMOS?</p><h2>Convirtamos una idea en un sistema.</h2></div><a href="mailto:yeisonrojas03@gmail.com">Escríbeme <Icon name="arrow" /></a></div></section>
}
function ProjectDialog({ project, close }: { project: Project; close: () => void }) { return <div className="dialog-backdrop" role="presentation" onMouseDown={close}><article className={`project-dialog ${project.impact ? 'has-impact' : ''}`} role="dialog" aria-modal="true" aria-labelledby="project-title" onMouseDown={event => event.stopPropagation()}><header><div><p className="kicker">{project.eyebrow} · {project.number}</p><h2 id="project-title">{project.title}</h2></div><button className="dialog-close" onClick={close} aria-label="Cerrar detalle"><Icon name="close" /></button></header><p className="dialog-description">{project.description}</p>{project.impact && <section className="impact-showcase"><div className="impact-heading"><p className="detail-label">IMPACTO EN LA OFICINA</p><span><i /> OPERACIÓN ACTIVA</span></div><div className="impact-grid">{project.impact.map(item => <article key={item.title}><strong>{item.title}</strong><small>{item.detail}</small></article>)}</div></section>}<div className="detail-grid"><section><p className="detail-label">ANTES</p><p>{project.challenge}</p></section><section><p className="detail-label">RESULTADO POSITIVO</p><p>{project.outcome}</p></section></div><Flow flow={project.flow} tone={project.tone} /><section className="demo-frame"><div className="demo-topbar"><i /><i /><i /><span>evidencia del proyecto</span></div><p>{project.proof}</p></section><footer className="project-links"><a href={project.repository} target="_blank" rel="noreferrer"><span><Icon name="github" /> Ver repositorio</span></a><span><Icon name="spark" /> {project.status}</span></footer></article></div> }
function Flow({ flow, tone }: { flow: string[]; tone: Project['tone'] }) { return <section className={`flow flow-${tone}`}><p className="detail-label">FLUJO DEL SISTEMA</p><div className="flow-steps">{flow.map((step, index) => <div className="flow-step" key={step}><span>{String(index + 1).padStart(2, '0')}</span><b>{step}</b></div>)}</div></section> }
export default App
